<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					- Registre suas avaliações.
				</div>
				<div class="communicationItem">
					- Anote emails importantes.
				</div>
				<div class="communicationItem">
					- Registre seus blocos importantes da faculdade.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form>
			<div class="row">
				<div class="col">
					<input type="text" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="text" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<!-- <img src="/img/agenda.jpg" /> -->
				<h1 class="title">📅 AgendaAluno</h1>
                <h4 class="mono">"Anote suas principais informações a respeito da sua vida acadêmica".</h4>

				<h2 class="mt-5 subtitle">Crie sua conta para conhecer melhor nosso trabalho.</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>