<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <h2 class="mono text-primary">📅 AgendaAluno</h2>
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" class="form-control" value="<?= $this->view->usuario['nome'] ?>" name="nome" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input type="text" class="form-control" value="<?= $this->view->usuario['email'] ?>" name="email" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" class="form-control" value="<?= $this->view->usuario['senha'] ?>" name="senha" placeholder="Senha">
              </div>
            
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

              <?php 
                if($this->view->erroCadastro) {
                  echo '<div class="alert alert-danger" role="alert">
                         Erro ao cadastrar usuário, preencha os dados corretamente!
                        </div>';
                }

                if($this->view->erroCadastroSenha) {
                  echo '<div class="alert alert-danger" role="alert">
                          Senhas não conferem.
                        </div>';
                }

                if($this->view->erroCadastroEmail) {
                  echo '<div class="alert alert-danger" role="alert">
                          E-mail inválido.
                        </div>';
                }


              ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  