<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/dashboard">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
	  </div>
          <h1>📅 AgendaAluno</h1>
      <a href=""></a>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">

						</div>

						<div class="col">
						</div>

						<div class="col">
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form>
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">aaaa</button>
						</div>

					</form>
				</div>
			</div>

			<div class="row tweet">
				<div class="col">
					<p><strong>Nome</strong> <span class="text text-muted">- data</span></p>
					<p>Conteúdo</p>

					<br />
					<form>
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>
				</div>
			</div>

			<div class="row ">
				<div class="col">
					<p><strong>Nome do Usuário</strong> <span class="text text-muted">- data</span></p>
					<p>Conteúdo</p>

					<br />
					<form>
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>		
				</div>
			</div>


		</div>


		<div class="col-md-3">
			<div class="">
				<span class="">naosei</span><br />
				<hr />
				<a href="#" class=""></a>
			</div>
		</div>

	</div>
</div>